# Generated by Django 2.1.4 on 2018-12-12 10:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('credit_score', models.IntegerField(default=100, verbose_name='信用分')),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.User')),
                ('token', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
