# Generated by Django 2.1.4 on 2018-12-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_credit_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SMS',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='1', max_length=15, verbose_name='密码'),
        ),
    ]
