# Generated by Django 2.1.4 on 2018-12-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181215_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='悦租房用户', max_length=15, verbose_name='用户名'),
        ),
    ]
