# Generated by Django 2.1.4 on 2018-12-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=15, verbose_name='房屋名称')),
                ('cover', models.URLField(max_length=100, verbose_name='封面')),
                ('city', models.CharField(max_length=10, verbose_name='所在城市')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('area', models.CharField(max_length=10, verbose_name='面积')),
                ('facility', models.CharField(max_length=100, verbose_name='设施')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评价人数')),
                ('comment_score', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='评分')),
            ],
        ),
    ]
