# Generated by Django 2.1.4 on 2018-12-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.IntegerField(choices=[(0, '空闲')], default=0, verbose_name='订单状态'),
        ),
    ]
