# Generated by Django 2.1.4 on 2018-12-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='status',
        ),
    ]
