# Generated by Django 2.1.4 on 2018-12-17 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_houseoccupy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseoccupy',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='occupy', to='house.House'),
        ),
    ]
