# Generated by Django 2.1.4 on 2018-12-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '待付款'), (1, '已完成'), (2, '已取消')], default=0, verbose_name='订单状态'),
        ),
    ]
