# Generated by Django 2.1.4 on 2018-12-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_username'),
        ('order', '0002_auto_20181213_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
            preserve_default=False,
        ),
    ]
