# Generated by Django 2.1.4 on 2018-12-17 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20181217_0844'),
        ('order', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='house.House'),
            preserve_default=False,
        ),
    ]
