# Generated by Django 2.1.4 on 2018-12-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, '待付款'), (1, '已完成'), (2, '已取消'), (3, '已评价')], default=0, verbose_name='订单状态'),
        ),
    ]
